name: lotus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2
  http: ^0.13.6
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.1.5
  shared_preferences: ^2.3.0
  table_calendar: ^3.2.0
  flutter_spinkit: ^5.1.0
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  clipboard: ^0.1.3
  mime: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/robot_light.png
    - assets/images/robot_dark.png
    - assets/images/robot1.png
    - assets/images/robot2.png
    - assets/images/robot3.png
    - assets/images/btn_google_light.png
    - assets/images/default_avt.png
    - assets/images/bot_avatar.png

  
  fonts:
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter_18pt-Medium.ttf
          - asset: assets/fonts/Inter_18pt-Bold.ttf
          - asset: assets/fonts/Inter_18pt-Light.ttf
          - asset: assets/fonts/Inter_18pt-Regular.ttf
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
          - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
          