name: lotus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2
  http: ^0.13.6

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.1.5
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/robot1.png
     - assets/images/robot2.png
     - assets/images/btn_google_light.png
  
  fonts:
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter_18pt-Medium.ttf
          - asset: assets/fonts/Inter_18pt-Bold.ttf
          - asset: assets/fonts/Inter_18pt-Light.ttf
          - asset: assets/fonts/Inter_18pt-Regular.ttf
          